### ISSUE TITLE
Need these icons please!

### ISSUE THREAD

**Issue by lavyadrian** [L4ki/Flight-Plasma-Themes#1]
Can you add : HexChat, NVidia xserver settings, fsearch, calibre, evolution, Linux multimedia studio, LibreOffice launcher, tor browser, transmission and the trash please?
I love this icon theme! Thanks!

**Comment by L4ki** [comment]
Hi lavyadrian,  

I will try my best to add the icons you have asked for as soon as possible.

Greeting,

**Comment by lavyadrian** [comment]
> Hi lavyadrian,
> 
> I will try my best to add the icons you have asked for as soon as possible.
> 
> Greeting,

Awesome man! I've been looking forever for an icon theme with this flair but none could quite compare as they all mostly copy one another! This is great work and the only weaknesses are the number of icons and maybe a support for gnome!
Thanks you for the work!
